# Generated by Django 4.1.7 on 2023-05-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('guest_number', models.IntegerField()),
                ('table_choise', models.CharField(choices=[('Middle', 'Middle'), ('Center', 'Center'), ('Corner', 'Corner'), ('VIP', 'VIP')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('menu_item_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
